[package]
name = "develop-rust-plugin"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition = "2018"

[dependencies]
zellij-tile = "0.41.1"
uuid = { version = "1.7.0", features = ["v4"] }
